var english={
	"name": {
		"version": "1.6",
		"date": "2017-01-10",
		"name": "en"
	},
	"_front": {
		"Cancel": "Cancel",
		"Confirm": "Confirm",
		"About_Us": "About Us",
		"Account": "Account",
		"UP": "UP",
		"Libiray": "Library",
		"Help": "Help",
		"My_Account": "My Account",
		"Setting": "Setting",
		"Skin": "Skin",
		"Language": "Language",
		"Current_Language": "Current Language",
		"Printer": "Printer",
		"No_UP_printers_found": "No printers found",
		"Printer_Name_Cannot_Be_Empty": "Printer Name Cannot Be Empty.",
		"Failed_to_locate_WiFi": "Failed to locate WiFi",
		"Set_Success": "Set Succeeded",
		"Please_Enter_Password": "Please Enter Password",
		"Upgrade": "Upgrade",
		"Current": "Current",
		"Your_System_is_UPtodate": "Your System is UP-to-date",
		"Remind_me_of_the_new_version": "Remind me of the new version",
		"Update": "Update",
		"Privacy_Policy": "Privacy Policy",
		"privacy": "Please review Tiertime Privacy Policy to know about the details of data collection of Tiertime.You can choose to turn on or off the data collection function base on your preference.",
		"Details": "Details",
		"Skin_Color": "Skin Color",
		"Model_Color": "Model Color",
		"Basic": "Basic",
		"Login": "Login",
		"Username_or_Email": "Username or Email",
		"Sign_In": "Sign In",
		"Sign_Up": "Sign Up",
		"Forgot_Password": "Forgot Password?",
		"Login_Failed": "Login Failed",
		"User_Account_has_not_been_Activated": "User Account has not been Activated",
		"User_does_not_Existed": "User does not Existed",
		"Password_is_Incorrect": "Password is Incorrect",
		"Please_enter_your_username_and_password": "Please enter your username and password",
		"Please_enter_user_name": "Please enter user name",
		"Please_enter_your_password": "Please enter your password",
		"Network_Problems_and_Please_Try_Later": "Network Problems and Please Try Later",
		"Login_Timeout": "Login Timeout",
		"Printer_Management": "Printer Management",
		"Serial_Number": "Serial Number",
		"Activation_Status": "Activation Status",
		"Binding_Status": "Binding Status",
		"Activate": "Activate",
		"Activated": "Activated",
		"Bind": "Bind",
		"Unbind": "Unbind",
		"Success": "Success",
		"Unbind_Successfully": "Unbind Successfully",
		"Failed_to_Unbind": "Failed to Unbind",
		"Binding_Successfully": "Binding Successfully",
		"Activation_Succeeded": "Activation Succeeded",
		"Sign_out": "Sign out",
		"Username": "Username (3-20 Characters Starting with a Letter)",
		"Emailenter": "Email (Enter an Email Address)",
		"Password": "Password (6-32 Characters)",
		"Confirm_Password": "Confirm Password (Input Password Again)",
		"Registration_means_you_agree_with": "Registration means you agree with",
		"Tiertime_End_User_Agreement": "《Tiertime End User Agreement》",
		"Invalid_Username": "Invalid Username",
		"Invalid_Email_Address": "Invalid Email Address",
		"Invalid_Password": "Invalid Password",
		"Passwords_Do_Not_Match": "Passwords Do Not Match",
		"Registration_Successful": "Registration Successful",
		"Congratulations": "Congratulations",
		"success_text": "Registration is successful. An activation code has been sent to your email account. Please click the link in your email to activate your account.",
		"Email": "Email",
		"Error": "Error",
		"Email_or_Username_Error": "Email or Username Error",
		"An_email_to_reset_your_password_has_been_sent_to_your_email_address": "An email to reset your password has been sent to your email address",
		"Failed_to_Reset_Password": "Failed to Reset Password",
		"Home": "Home",
		"Import_Model_or_Image": "Import Model or Image",
		"Print": "Print",
		"Initialize_Printer": "Initialize Printer",
		"Calibrate": "Calibrate",
		"Maintenance": "Maintenance",
		"Move": "Move",
		"Scale": "Scale",
		"More": "More",
		"View": "View",
		"Undo": "Undo",
		"Auto_Place": "Auto Place",
		"Rotate": "Rotate",
		"Mirror": "Mirror",
		"Save_Model": "Save Model",
		"Reset_to_Default": "Reset to Default",
		"Fix_Errors": "Fix Errors",
		"Merge": "Merge",
		"Delete": "Delete",
		"Top_View": "Top View",
		"Bottom_View": "Bottom View",
		"Back_View": "Back View",
		"Free_View": "Free View",
		"Right_View": "Right View",
		"Front_View": "Front View",
		"Left_View": "Left View",
		"Wait_a_moment": "Wait a moment...",
		"Range_is_from": "Range is from",
		"No_Axis_Chosen": "No Axis Chosen",
		"Add": "Add",
		"Add_Picture": "Add Picture",
		"Add_Mode": "Add Model",
		"Saving": "Saving",
		"Printer_Setting": "Printer Setting",
		"Normal": "Normal",
		"Layer_Thickness": "Layer Thickness",
		"Infill": "Infill",
		"Quality": "Quality",
		"Fine": "Fine",
		"Fast": "Fast",
		"Turbo": "Turbo",
		"Option": "Option",
		"Preference": "Preference",
		"Dormancy": "Sleep",
		"Preview": "Preview",
		"Select_Saved_Slot": "Select Saved Slot",
		"Reprint": "Reprint",
		"Slot": "Slot",
		"Number": "NO.",
		"Model_Name": "Model Name",
		"Time": "Time",
		"Date": "Date",
		"Choose": "Choose",
		"Part": "Part",
		"Surface": "Surface",
		"Angle": "Angle",
		"Support": "Support",
		"Dense": "Dense",
		"Area": "Area",
		"Space": "Space",
		"No_Raft": "No Raft",
		"No_Support": "No Support",
		"Stable_Support": "Stable Support",
		"Others": "Others",
		"Unsolid_Model": "Unsolid Model",
		"Thin_Wall": "Thin Wall",
		"Preheat": "Preheat",
		"Default": "Default",
		"Calibration": "Calibration",
		"Platform_Calibration": "Platform Calibration",
		"Manual": "Manual",
		"Auto_Level": "Auto Level",
		"Reset": "Reset",
		"Nozzle_Height": "Nozzle Height",
		"Set": "Set",
		"Nozzle_Detect": "Nozzle Detect",
		"Demo_Op": "Demo Op.",
		"Demo_Op_Over": "Demo Op. Over",
		"Set_nozzle_height_is": "Set nozzle height is:",
		"Compensation": "Compensation",
		"Set_Nozzle_Height_as": "Set Nozzle Height as ",
		"Extrude": "Extrude",
		"Withdraw": "Withdraw",
		"Stop": "Stop",
		"Material": "Material",
		"Weight": "Weight",
		"Customized": "Customized",
		"Customized_Material": "Customized Material",
		"Name": "Name",
		"Nozzle": "Nozzle(℃)",
		"Platform": "Platform(℃)",
		"Process": "Process",
		"Please_sign_in_your_account": "Please sign in your account",
		"Material_Name_Duplicated": "Error:Material Name Duplicated",
		"Only_7_Materials_Allowed": "Only 7 Materials Allowed",
		"Fields_can_not_be_Empty": "Fields can not be Empty",
		"Stop_Printing": "Stop Printing",
		"Pause": "Pause",
		"Resume": "Resume",
		"Stop_Preview": "Stop Preview",
		"Stop_the_Current_Print_Job": "Confirm to Stop?",
		"Time_Left": "Time Left",
		"h": "h",
		"m": "m",
		"s": "s",
		"Slicing": "Slicing ",
		"Sending": "Sending ",
		"offical_initerface": "Official Material",
		"series_number": "Serial Number",
		"serial_password": "Password",
		"please_series_number": "Please Enter The Serial Number",
		"My_model": "My Model",
		"Public_model": "Featured",
		"Self_model": "Private",
		"Save_model": "Liked",
		"Share_model": "Published",
		"Buy_model": "Purchased",
		"My_print": "My 3D Printer",
		"Find_all_print": "View All Printers",
		"User_number": "User Credits",
		"Change_password": "Modify Password",
		"upload_model": "Upload Model",
		"upload": "Upload",
		"upload_list": "Upload List",
		"readmessage": "Preparing Data......",
		"All": "All",
		"Free": "Free Models",
		"Pay": "Paid Models",
		"Model_parameter": "Model Parameters",
		"Model_Size": "Size",
		"Model_price": "Points",
		"Model_filder": "File",
		"Print_count": "Print Times",
		"Model_buy": "Buy",
		"Model_save": "Like",
		"Model_al_save": "Liked",
		"Model_download": "Download",
		"Model_deleat": "Delete",
		"Model_desript": "Description",
		"Model_name": "Name",
		"Download_on": "Download",
		"Model_share": "Share",
		"Cancel_upload": "Cancel Publish Process",
		"All_download": "Download All",
		"All_open": "Open All",
		"Model_attr": "Model Attributes",
		"Model_information": "Model Infomation",
		"Filepath": "File Path:",
		"Size": "Model Size:",
		"Min_Size": "Min Pos:",
		"Max_Size": "Max Pos:",
		"Vertex_Number": "Vertex Number:",
		"Facet_Number": "Facet Number:",
		"Volume": "Volume:",
		"Surface_Area": "Area:",
		"Inch": "Inch",
		"Mm": "mm",
		"Alerady_buy": "Purchased",
		"Manage" : "Manage",
		"Model_unit": "Unit:",
		"Auto_height_end": "Nozzle height detection ended",
		"Flex_plat": "Flex",
		"Ward_plat": "Perforated",
		"Model_upload": "Publish",
		"Model_points": "Points",
		"Unlimited": "Unlimited",
		"Error_prompt": "Error",
		"Connection_failed": "Connection failed",
		"User_and_password": "User name and password can not be empty",
		"User_and_password_already": "User name or mailbox already exists",
		"Calibration_failure_temp_hot": "Calibration failed, nozzle temperature is too high",
		"Member_login_in_auto": "Auto Login",
		"Model_list_nav": "Navigation",
		"Model_share_cancle":  "Canceled",
		"Keep_on_download": "Continue",
		"Model_buy": "Buy",
		"Model_preparing":"Preparing data, can not close",
		"LatestVersion": "Latest Version V.",
		"Failed_to_bind": "Binding failed",
		"Custom_material_information_empty":"Custom material information can not be blank",
		"Clear_cache": "Clean up cache",
		"Clear_download_model": "Clear downloaded models",
		"Clear_cache_file": "Clear cache file",
		"Compensation_height": "Nozzle offset",
		"Current_nozzle_height_print": "Nozzle height",
		"Model_insert": "Insert",
		"Advanced_print": "Advanced Print",
		"Pause_position": "Pause position",
		"Pause_height": "Height",
		"Print_cao": "Print slot",
		"Pause_print_exame": "Enter the height (mm) to be paused For example: 7.6",
		"Model_audit": "Under review",
		"Model_re_publish": "Republish",
		"Cancel_clear_up": "Cancel",
		"Clear_finish": "Cleanup Complete",
		"Nozzle_diameter": "Nozzle Diam",
		"Infill_wrap": "Shell",
		"Infill_surface": "Surface",
		"Infill_style1": "13%",
		"Infill_style2": "15%",
		"Infill_style3": "20%",
		"Infill_style4": "65%",
		"Infill_style5": "80%",
		"Infill_style6": "99%",
		
		"Manual_activation": "Manual activation",
		"Manual_file": "Please load active.code file to activate the printer",
		"Copy_message": "Copy information to clipboard",
		"Manual_fail": "Failed to return activation code from server",
		"Manual_download": "Loading",
		"Manual_connecting": "Activating, please wait ...",
		"Platform_leval": "Level Calibration",
		"Platform_vertival": "Vertical Calibration",
		"Model_default_color": "Default",
		"Model_color_design": "Edit",
		"Manual_have_code": "If you already have an activation code, you can try",
		"Manual_copy_success": "Copy successful",
		"Infinite_print_price": "Unlimited Printing Credits",
		"Once_print_price": "Single-pass printing",
		"Model_print_price": "Print Price",
		"Print_infinite": "Unlimited",
		"Model_buy_times": "Purchases",
		"Manual_email": "If you do not have this file, you can log in",
		"Model_publish_limited": "Unlimited price can not be less than the price of a single model",
		"Manual_pass_information": "Via the following information:",
		"Manual_get_code":"Gets the active file ActiveCode.act, activates the printer manually",
		"Colud_Print":"Printing with Cloud Parameters"
	},
	"print": {
		"PrinterStatus-1": "Printer not Connected",
		"PrinterStatus0": "Printer not Initialized",
		"PrinterStatus1": "Printer Ready",
		"PrinterStatus2": "Print Job in Progress",
		"PrinterStatus3": "Print Job Paused",
		"PrinterStatus4": "Nozzle Error",
		"PrinterStatus5": "Motion System Error",
		"PrinterStatus6": "Print Job Finished",
		"PrinterStatus7": "Print Job Stopped",
		"PrinterStatus8": "Nozzle Too Hot",
		"PrinterStatus9": "Nozzle Too Cool",
		"PrinterStatus10": "Platform Too Hot",
		"PrinterStatus11": "tt_reserved_1",
		"PrinterStatus12": "tt_reserved_2",
		"PrinterStatus13": "tt_reserved_3",
		"PrinterStatus14": "tt_reserved_4",
		"PrinterStatus15": "System Powered ON",
		"PrinterStatus16": "SD Card Error",
		"PrinterStatus17": "SD Card Write Error",
		"PrinterStatus18": "SD Card Read Error",
		"PrinterStatus19": "Save to SD Card",
		"PrinterStatus20": "Joggle Error",
		"PrinterStatus21": "Copyright Limitation",
		"PrinterStatus22": "Print Number Limitation",
		"PrinterStatus23": "Communication Error",
		"ERROR": "ERROR",
		"ERROR: Task cannot be performed during printing": "ERROR: Task cannot be performed during on going print jobs.",
		"ERROR: Incorrect material": "ERROR: Incorrect Material.",
		"ERROR: Printer status error": "ERROR: Printer Status Error.",
		"ERROR: Printer connection error": "ERROR: Printer Connection Error.",
		"ERROR: Data transfer failure": "ERROR: Data Transfer Failure.",
		"ERROR: Printer is busy,please stop and try again": "ERROR: Printer is busy. Please wait until it stops and then try again.",
		"ERROR: Printer material shortage,still continue?": "ERROR: Printer is short of material, still continue?",
		"ERROR: Printer support material shortage,still continue?": "ERROR: Printer is short of support material, still continue?",
		"Correct range":"Correct range",
		"Repeat last print?": "Repeat Last Print?",
		"ERROR: Other error ": "ERROR: Other Errors.",
		"Language test": "Language Test",
		"Are you sure to stop the print job?": "Confirm to stop the current job?",
		"Found a new version": "A new version of software has been found",
		",download it immediately?": ",download it immediately?",
		"[YES]: Update immediately": "[YES]: Update Immediately",
		"[NO]: Remind me later": "[NO]: Remind Me Later",
		"[CANCEL]: Switch off update reminder": "[CANCEL]: Switch Off Update Reminder",
		"Note: Download will be running in the background, after the completion of the notice": "Note: Download will be running in the background. You will be notified after the completion .",
		"Update": "Update",
		"No new version": "No New Version.",
		"ERROR: Temperature is too high": "ERROR: Temperature is too high.",
		"ERROR: Sensor not connected": "ERROR: Sensor is not connected.",
		"ERROR: Calibration Failure": "ERROR: Calibration failed.",
		"ERROR: Printer is busy": "ERROR: Printer is busy.",
		"Success，Please reset nozzle height before printing": "Success: Please reset the nozzle height before printing.",
		"ERROR: Printer error": "ERROR: Printer Error.",
		"Print: ": "Print: ",
		"Material: ": "Material: ",
		"g": "g",
		"H": "H",
		"M": "M",
		"S": "S",
		"ERROR: Templete directory get error": "ERROR: Failed to locate the temporary directory.",
		"ERROR: Create dir error": "ERROR: Failed to create directory",
		"ERROR: Copy UpdateFile Error_APP": "ERROR: Failed to Copy Update File_APP",
		"ERROR: Copy UpdateFile Error_DLL": "ERROR: Failed to Copy Update File_DLL",
		"ERROR: Nozzleheight set error": "ERROR: Failed to Set Nozzle Height",
		"ERROR:Model does not exist": "ERROR: Model not found",
		"Activation": "Activation",
		"Please activate the printer in time to use the full printer functions": "Please activate the printer to use the full power of printers",
		"Activation state error, need to return to the factory": "Failed to activate the printer. Please contact the manufacturer.",
		"OK": "OK",
		"CANCEL": "CANCEL",
		"YES": "YES",
		"NO": "NO",
		"ABORT": "ABORT",
		"RETRY": "RETRY",
		"IGNORE": "IGNORE",
		"Save successful": "Save succeeded.",
		"Save failed": "Save failed.",
		"Downloading, please wait": "Download in progress. Please wait.",
		",upgrade now?": ",upgrade now?",
		"Level data save error": "Failed to Save Leveling Data.",
		"ERROR: Printer no response": "ERROR: Printer not Responding.",
		"ERROR: Printer password error": "ERROR: Incorrect Printer Password.",
		"ERROR: Printer connected by other clients": "ERROR: Printer is being used by other users.",
		"ERROR: Printer none certification": "ERROR: Printer is not certified.",
		"Connection OK": "Connection OK.",
		"Connection Error": "Connection Error.",
		"Activation is successful, please restart the printer": "Activation succeeded. Please restart the printer.",
		"Can not Save more than 4 millon facets model": "Cannot save models with more than 4 million facets.",
		"No Model Selected": "No model is selected",
		"warning!": "Warning!",
		"    Delete Selected Model?": "    Delete Selected Models?",
		"    Delete All Models?": "    Delete all of Models?",
		"Please close the front door": "Please Close the Front Door.",
		"Model is too large! Can not Load": "Model is too large. Loading Failed",
		"Loading Failed": "Loading Failed!",
		"Print job stopped at ": "Print Job Stopped at layer No.",
		"th layer, resume the print?": ". Resume the Print Job?",
		"ERROR:  Can not resume the broken print job": "Error: Can not resume the suspended print",
		"ERROR: Data transfer failed, try again?": "ERROR: Data Transfer Failed. Try again?",
		"OpenGL Version Too Low! Check your Graphic Drivers!": "Please upgrade OpenGL, and check your graphic card drivers!",
		"ERROR: Printer SN Error": "ERROR: Printer Serial Number Error",
		"ERROR: Unknow error": "ERROR: Unknown Error",
		"ERROR: Invalide activekey": "ERROR: Invalid Activation Key",
		"ERROR: No factory actived": "ERROR: Not Factory Activated",
		"ERROR: Active error,wrong key": "ERROR: Activation Error. Invalid Key",
		"ERROR: The server returns the activation code to parse the JSON failed": "ERROR: Activation data returned from server failed.",
		"ERROR: The server failed to return the activation code": "ERROR: The server failed to return the activation code",
		"ERROR: Failed to get the check code from the printer": "ERROR: Failed to get the checksum data from the printer",
		"ERROR: The current state of activation is not factory activation": "ERROR: The current activation status is not factory activation",
		"ERROR: Failed to obtain an active state": "ERROR: Failed to obtain the activation status.",
		"ERROR: Model out of print bound": "ERROR: Model out of Bound of Print Area",
		"ERROR: Server connection failed": "ERROR: Server Connection Failed",
		"ERROR: Verification Failed,Please download activation package": "ERROR: Verification Failed. Please Download Activation Package",
		"Please Select The Type Of Plat": "Please Select the Type Of Plat",
		"ERROR: Temperature is low": "ERROR: Temperature is Low",
		"Do you want to keep current model?": "Do you want to keep current model?",
		"ERROR: Image read failed": "Error: Image import failed",
		"Multiple": "Multiple",
		"ERROR：Please select the model you need to upload": "Error: Please select the model you need to uplaod",
		"Initialize_Printer": "Initialize Printer",
        "ERROR: Material modification failure": "ERROR: Material modification failure",
        "Price":"Price",
		"Point":"Point",
		"Sure to buy":"Do you want get this project",
		"ERROR: Upload Error": "ERROR: Upload Error",
        "ERROR: Network Disconnection": "ERROR: Network Disconnection",
        "ERROR: Cancel publish failure":"ERROR: Cancel publish failure",
        "The printer does not support this feature":"The printer does not support this feature",
        "Print finished, please take out the model":"Print finished, please take out the model",
        "Cancel":"Cancel",
		"Not Prompt":"Not Prompt",
		"No material detected, please replace it":"No material detected, please replace it",
		"ERROR: Publish failure":"ERROR: Publish failure",

		"ERROR:Gcode failed to run":"ERROR:Gcode failed to run",
		"Run File":"Run file",
		"ERROR: Input Not Valid":"ERROR: Input Not Valid",
		"Select active file":"Select active file",
		"ERROR: X1 Or X2 Input Error":"ERROR: X1 Or X2 Input Error",
		"ERROR: Z Or H Input Error":"ERROR: Z Or H Input Error",
		"ERROR: Save Error":"ERROR: Save Error",
		"ERROR: User Not Login":"ERROR: User Not Login",
		"ERROR: Model validation failure":"ERROR: Model validation failure",
		"Can Not Open File!":"Can Not Open File!",
		"Can Not Verify File!":"Can Not Verify File!",
		"User Does Not Match!":"User Does Not Match!"
	},
	"graphic": {
		"Filepath: ": "File Path: ",
		"Size: ": "Size: ",
		"Min-Size: ": "Min-Size: ",
		"Max-Size: ": "Max-Size: ",
		"Vertex Number: ": "Vertex Number: ",
		"Facet Number: ": "Facet Number: ",
		"Volume: ": "Volume: ",
		"Copying...": "Copying Models ...",
		"Saveing...": "Saving Models ...",
		"has scaled from inch unit to mm unit!": "Model is too small,Enlarged by 25.4 times!",
		"Property": "Property",
		"Merge": "Merge Model",
		"Copy": "Copy",
		"1 model": "1 Copy",
		"2 model": "2 Copys",
		"5 model": "5 Copys",
		"Delete": "Delete",
		"Delete All": "Delete All",
		"Select All": "Select All",
		"UnSelect All": "Unselect All",
		"Initialize View": "Initialize View",
		"Rotate By Models Center": "Rotate around the Center of Models",
		"Exit": "Exit",
		"app is not verified":"App is not verified",
		"The file is damaged": "The file is damaged",
		
		"current models contain protected model! can not do this operation!":"Current models contain protected model! Can not do this operation!",
		"UnKnown ERROR!Please Contact TierTime!":"UnKnown ERROR!Please Contact TierTime!"
	},
	"image_front": {
		"_Model_Height": "Model Height",
		"_Base_Height": "Base Height",
		"_Style": "Style",
		"_Model_Size": "Model Size",
		"_Unit": "Unit(mm)",
		"_Pen_Size": "Pen Size",
		"_Pen_Color": "Pen Color",
		"_Pen_Type": "Pen Type",
		"_Erase_Size": "Erase Size",
		"_Font": "Font",
		"_Font_Size": "Font Size",
		"_Font_Color": "Font Color",
		"_Constrain": "Constrain",
		"_Tools": "Tools",
		"_Setting": "Setting",
		"_Previous": "Previous",
		"_Apply": "Apply",
		"_Go_back": "Back",
		"_Pen": "Pen",
		"_Rubber": "Eraser",
		"_Text": "Text",
		"_Cut": "Crop",
		"_Toggle_color": "Toggle color"
	},
	"IOS_Ipad_Iphone": {
    "Version": "1.0.1",
    "name": "en",
    "Stop": "Stop",
    "Extrude": "Extrude",
    "WithDraw": "Withdraw",
    "SN": "NO.",
    "ModelName": "Model Name",
    "Archive": "Slot",
    "Infill": "Infill",
    "Register_success": "Registation Succeeded",
    "Congratulation": "Congratulation",
    "ActivationCode": "Registation succeeded. An activation code has been sent to your email box. Please click the link in the email and activate your account.",
    "systemError": "System Error",
    "tt_systemunlink": "Printer not Connected",
    "tt_systemerror": "No Initialized",
    "tt_prepared": "Printer Ready",
    "tt_runing": "Printing",
    "tt_pause": "Printing Paused",
    "tt_nozzleerror": "Nozzle Error",
    "tt_motionerror": "Motion System Error",
    "tt_finished": "Print Job Finished",
    "tt_userstop": "Print Job Stopped",
    "tt_temphigh": "Nozzle Too Hot",
    "tt_templow": "Nozzle Too Cool",
    "tt_workroomhigh": "Platform Too Hot",
    "tt_reverse_1": "tt_reverse_1",
    "tt_reverse_2": "tt_reverse_2",
    "tt_reverse_3": "tt_reverse_3",
    "tt_reverse_4": "tt_reverse_4",
    "tt_systempoweron": "System Powered ON",
    "tt_sdcarderror": "SD Card Error",
    "tt_sdwberror": "SD Card Write Error",
    "tt_sdrberror": "SD Card Read Error",
    "tt_savetosd": "Save to SD Card",
    "tt_jogcmderror": "Joggle Error",
    "tt_copyrightzero": "Copyright Restricted",
    "tt_printtimelimit": "Print Number Reach Limitation",
    "tt_commerror": "Communication Error",
    "printerName": "Printer Name",
    "nozzleTemperature": "Nozzle TEMP",
    "flatTemperature": "Plate TEMP",
    "m_nMaterial": "Material",
    "m_dNozzleHeight": "Nozzle Height",
    "btn_aboutUs": "About Us",
    "btn_myCounts": "Account",
    "btn_up": "UP",
    "btn_libiray": "Library",
    "btn_help": "Help",
    "dialogTitle_add": "ADD",
    "dialogAdd_photo": "Add Photo",
    "dialogAdd_stl": "Add Model",
    "dialogTitle_layer": "Setting",
    "dialogTitle_Z_resolution": "Layer Thickness",
    "dialogTitle_part": "Part",
    "dialogTitle_Surface": "Surface",
    "dialogTitle_Surface_SupportAngle": "Angle",
    "dialogTitle_Support": "Support",
    "dialogTitle_Dense": "Dense",
    "dialogTitle_Support_Angle": "Angle",
    "dialogTitle_Support_Area": "Area",
    "dialogTitle_Support_Space": "Space",
    "dialogTitle_Stable_Support": "Stable Support",
    "dialogTitle_Fill": "Infill",
    "dialogTitle_fill_shell": "Shell",
    "dialogTitle_fill_surface": "Surface",
    "dialogTitle_fill_solid": "Solid",
    "dialogTitle_fill_Loose": "Loose",
    "dialotTitle_fill_Hollow": "Hollow",
    "dialogTitle_fill_BigHole": "Big Hole",
    "ResettoDefault": "Default",
    "save": "Save",
    "unsave": "Cancel",
    "dialogTitle_Maintain": "Maintenance",
    "dialogTitle_Maintenance": "Maintenance",
    "dialogTitle_Extrude": "Extrude",
    "dialogTitle_Evacuate": "Withdraw",
    "Weight": "Weight",
    "dialogTitle_PrinterSetting": "Printer Setting",
    "dialogTitle_printerName": "Printers",
    "dialogTitle_UnsolidModel": "Unsolid Model",
    "dialogTitle_NoRaft": "No Raft",
    "dialogTitle_heat": "Keep Heating",
    "dialogTitle_Quality": "Quality",
    "option": "Option",
    "reprint": "Reprint",
    "preview": "Preview",
    "dialogTitle_Calibrate": "Calibration",
    "platMainH3": "Platform Correction",
    "printBtn": "Print",
    "exit": "Exit",
    "save3DModeling_txt": "Saving",
    "ImgTo3D_txt": "Converting",
    "Time_left": "Time",
    "initialPrinter": "Initializing",
    "logIn": "Sign in",
    "preference": "Preference",
    "no_Support": "No Support",
    "thinWall": "Thin Wall",
    "others": "Others",
    "autoPlace": "Auto Place",
    "noRecentFile": "No Recent File",
    "autoUpdateTxt": "Please remind me of the new version",
    "apError": "Wifi Error",
    "auto": "Auto",
    "manual": "Manual",
    "platAutoIng": "Plate Auto Calibration",
    "nozzleAutoIng": "Nozzle Auto Calibration",
    "autoError": "Sensor not Connected",
    "errorTxt": "Error",
    "successTxt": "Success",
    "connectTxt": "Connecting...",
    "setSuccessTxt": "Value Set Succeeded",
    "setErrorTxt": "Value Set Failed",
    "convert": "Converting",
    "nozzleHeating": "Wait a moment",
    "math": "Slicing",
    "transfer": "Transfering",
    "normal": "Normal",
    "fine": "Fine",
    "fast": "Fast",
    "turbo":"Turbo",
    "timeH": "h",
    "timeM": "m",
    "timeS": "s",
    "connectSuccessTxt": "Connection Succeeded",
    "connectErrorTxt": "Connection Failed",
    "languageTxt": "Language",
    "PrinterTxt": "Printer",
    "wifiTxt": "Wifi",
    "UpdateTxt": "Update",
    "currentTxt": "Current",
    "newTxt": "Latest",
    "axisTxt": "No Axis Direction Chosen",
    "yes": "Confirm",
    "no": "Cancel",
    "printerInitTips": "Initialized Printer?",
    "printerStopTips": "Stop printing?",
    "manualUpdate": "Update",
    "justTxt1": "Just enter",
    "justTxt2": "number",
    "nameError": "Printer name cannot be empty",
    "custom": "Customized",
    "txtObject": "Object",
    "share": "Share",
    "verTips": "Your system is UP-to-date ",
    "nozzleCurrentHeight": "Nozzle Current Height",
    "nozzleSetHeight": "Nozzle Height",
    "reset": "Reset",
    "compensation": "Leveling",
    "pausePrintError": "Pause Print Error",
    "resumePrintError": "Resume Print Error",
    "nozzleTo": "Move",
    "set": "Set",
    "detectNozzle": "Detect Nozzle",
    "autoLevel": "Auto Level",
    "saveSetNozzleHeight": "Save nozzle height as ",
    "intNumberTips": "Range is from",
    "connectWifiError0x110": "Password error",
    "connectWifiError0x111": "Connected by other clients",
    "connectWifiError0x112": "Not Certified",
    "connectWifiError0x113": "Connection Failed",
    "connectWifiError0": "No Response",
    "connectWifiError2": "Printer Busy",
    "connectWifiErrorUnknown": "Unknown Error",
    "sync_tips_resetPrinter": "Reset Printer",
    "checkNetwork": "Please make sure the printer and the mobile device are in the same network",
    "previewStopTips": "Stop Preview?",
    "ios_Font_WordStyle": "WordStyle",
    "ios_Font_Keyboard": "Keyboard",
    "ios_Font_Finish": "Finish",
    "ios_Font_ChangeText": "Change Text:",
    "ios_Font_Font": "Font",
    "ios_Font_PleaseChangWord": "Please click to enter text ",
    "ios_Alert_Message": "Model has been imported. Open it now? ",
    "ios_Alert_cancel": "Cancel",
    "ios_Alert_OK": "OK",
    "ERROR": "ERROR",
    "ERROR: Task cannot be performed during printing": "ERROR: Task cannot be performed during printing",
    "ERROR: Incorrect material": "ERROR: Incorrect material",
    "ERROR: Printer status error": "ERROR: Printer status error",
    "ERROR: Slicing error": "ERROR: Slicing error",
    "ERROR: Printer connection error": "ERROR: Printer connection error",
    "ERROR: Data transfer failure": "ERROR: Data transfer failure",
    "ERROR: Printer is busy,please stop and try again": "ERROR: Printer is busy. Please try again later",
    "ERROR: Printer material shortage,still continue?": "ERROR: Printer is short of material. Still continue?",
    "ERROR: Printer support material shortage,still continue?": "ERROR: Printer is short of support material. Still continue?",
    "ERROR: Nozzleheight set error Correct range:": "ERROR: Nozzle height set error. Correct range:",
    "Repeat last print?": "Repeat last print?",
    "ERROR: Other error ": "ERROR: Other error ",
    "Language test": "Language test",
    "Are you sure to stop the print job?": "Stop the print job?",
    "Found a new version": "Found a new version",
    ",download it immediately?": ", download it now?",
    "[YES]: Update immediately": "[YES]: Update now",
    "[NO]: Remind me later": "[NO]: Remind me later",
    "[CANCEL]: Switch off update reminder": "[CANCEL]: Switch off update reminder",
    "Note: Download will be run in the background, after the completion of the notice": "Note: Download will be running in the background. You will be notified after the completion",
    "Update": "Update",
    "No new version": "No new version",
    "ERROR: The model is opening, please try again later": "ERROR: A model is being loaded. Please try again later.",
    "ERROR: Temperature is too high": "ERROR: Temperature is too high",
    "ERROR: Sensor not connected": "ERROR: Sensor is not connected",
    "ERROR: Calibration failure": "ERROR: Calibration failure",
    "ERROR: Printer is busy": "ERROR: Printer is busy",
    "Success，Please reset nozzle height before printing": "Platform leveling succeeded. Please reset the nozzle height before printing.",
    "ERROR: Printer error": "ERROR: Printer error",
    "Print: ": "Print: ",
    "Material: ": "Material: ",
    "g": "g",
    "H": "H",
    "M": "M",
    "S": "S",
    "ERROR: Templete directory get error": "ERROR: Failed to locate the temporary directory.",
    "ERROR: Create dir error": "ERROR: Failed to create directory",
    "ERROR: Copy UpdateFile Error_APP": "ERROR: Failed to copy update Error_APP",
    "ERROR: Copy UpdateFile Error_DLL": "ERROR: Failed to copy update Error_DLL",
    "ERROR: Nozzleheight set error": "ERROR: Failed to set nozzle height",
    "ERROR:Model does not exist": "ERROR: Model not found",
    "Activation": "Activation",
    "Please activate the printer in time to use the full printer functions": "Please activate the printer to use the full power of UP Printers",
    "Activation state error, need to return to the factory": "Failed to activate the printer. Please contact the manufacturer.",
    "OK": "OK",
    "CANCEL": "CANCEL",
    "YES": "YES",
    "NO": "NO",
    "ABORT": "ABORT",
    "RETRY": "RETRY",
    "IGNORE": "IGNORE",
    "Save successful": "Save Succeeded",
    "Save failed": "Save Failed",
    "Downloading, please wait": "Download in progress. Please wait.",
    ",upgrade now?": ", upgrade now?",
    "Level data save error": "Failed to save leveling data.",
    "ERROR: Printer no response": "ERROR: Printer not responding",
    "ERROR: Printer password error": "ERROR: Incorrect printer password",
    "ERROR: Printer connected by other clients": "ERROR: Printer is being used by other users",
    "ERROR: Printer none certification": "ERROR: Printer is not certified",
    "Connection OK": "Connection OK",
    "Connection Error": "Connection Error",
    "Activation is successful, please restart the printer": "Activation succeeded. Please restart the printer",
    "Can not Save more than 4 millon facets model": "Cannot save models with more than 4 million facets.",
    "Please close the front door": "Please close the front door",
    "Can not Open more than 1 millon facets temporarily in WIN32 System": "Cannot open model with more than 1 millon facets in WIN32 System",
    "Print job stopped at ": "Print job stopped at layer No.",
    "th layer, resume the print?": ". Resume the print job?",
    "ERROR: Can not resume the broken print job": "ERROR: Cannot resume the suspended print job",
    "ERROR: Data transfer failed, try again?": "ERROR: Data transfer failed. Try again?",
    "OpenGL Version Too Low! Check your Graphic Drivers!": "Please upgrade OpenGL, and check your graphic card drivers!",
    "UnknownName": "Unknown Name",
    "Please input": "Please input ",
    "link password": "link password",
    "Enter password": "Enter password",
    "Join": "JOIN",
    "Joining": "Joining ",
    "Cannot Join": "Cannot join ",
    "user_login": "Login",
    "user_name_hint": "Email/Username",
    "password_hint": "Password",
    "sign_in": "Login in",
    "sign_up": "Sign up",
    "ifremember": "Remember Me",
    "forget_password": "Forgot password?",
    "username": "Username",
    "email": "Email",
    "ConfirmPassword": "Confirm password",
    "username_error": "Username is illegal",
    "email_error": "email is illegal",
    "password_error": "password is illegal",
    "confirm_error": "two passwords are different",
    "registration_statement": "You registration means you agree with",
    "agreement": "'Tiertime user agreement'",
    "login_info": "Printer Management",
    "online_device": "Device Online",
    "Device_List": "My Printers",
    "my_device": "My Devices",
    "net_error": "Internet is down. Please try later.",
    "device_sn": "NO.",
    "activate_status": "Activation Status",
    "bind_status": "Binding Status",
    "activate": "Activate",
    "activated": "Activated",
    "bind": "Binding Status",
    "binded": "Bound",
    "unbind": "Unbind",
    "EmailWrong": "User name or email error",
    "UserNameExisted": "User name has been used",
    "EmailExisted": "Email has been used",
    "unactive": "Unactive",
    "PasswordErr": "Password Error",
    "ERROR: Printer SN Error": "ERROR: Printer SN Error",
    "ERROR: Unknow error": "ERROR: Unknow Error",
    "ERROR: Invalide activekey": "ERROR: Invalide Activation Key",
    "ERROR: No factory actived": "ERROR: Not Activated by Factory",
    "ERROR: Active error,wrong key": "ERROR: Activation Error. Invalid Key",
    "ERROR: The server returns the activation code to parse the JSON failed": "ERROR: Activation data returned from server is invalid",
    "ERROR: The server failed to return the activation code": "ERROR: The server failed to return activation code",
    "ERROR: Failed to get the check code from the printer": "ERROR: Failed to get the checksum data from the printer",
    "ERROR: The current state of activation is not factory activation": "ERROR: The current activation status is not factory activation",
    "ERROR: Failed to obtain an active state": "ERROR: Failed to obtain the activation status.",
    "No Model saved for reprint": "No Model saved for reprint",
    "LoginError:User does not exist": "User does not exist",
    "LoginError:Password Error": "Password Error",
    "LoginError:User not activated": "User not Activated",
    "LoginError:Purchase of goods not registered": "The goods for sale is not registered",
    "LoginError:Registration parameter is not complete": "Registration parameter is not complete",
    "LoginError:Registration parameter check error": "Registration Parameter Error",
    "LoginError:User already exists": "User Already Exists",
    "LoginError:Data save failed": "Failed to Save Data",
    "LoginError:Network connection timeout": "Network Connection Timeout",
    "LoginError:Login failed,please try again": "Login failed. Please try again",
    "The print model beyond the range": "The print model beyond the range",
    "Password has been successfully sent to the mailbox": "Password has been successfully sent to the mailbox",
    "Sign_out": "Sign out",
    "ERROR: Validation failure!": "ERROR: Validation failure!",
    "Logining...": "Logging in...",
    "Set_InitPrinter": "Initialize",
    "Set_StopPreview": "Stop Preview",
    "Set_StopPrint": "Stop Printing",
    "Set_Delete": "Delete",
    "Set_SelectPrinter": "Select Printer",
    "Set_MaterialName": "Name",
    "Set_MaterialInputName": "Please input name",
    "Set_MaterialInputTemp": "Please input temperature",
    "Set_Custom": "Customize",
    "Set_PlesaeInputMaterialName": "Enter material name",
    "Set_PleaseInput1-5Character": "Please enter a string with 1-5 characters",
    "Set_NameExist": "Name already exists",
    "Set_Please enter a temperature value": "Please enter a temperature value",
    "Set_The temperature is not legitimate, please enter 0-300 numbers": "The temperature is not valid. Please enter a number between 0-300",
    "Set_The temperature is not legitimate, please enter 0-100 numbers": "The temperature is not valid. Please enter a number between 0-100",
    "Set_incomplete parameters": "Parameters Incomplete",
    "Set_Customize the amount of material can not be more than 4": "4 customized materials are allowed",
    "Can not use special characters": "Can not use special characters",
    "Pause Printing": "Pause",
    "Resume printing": "Resume",
    "Quality Model": "Featured",
    "Private Model": "Private",
    "Collected Model": "Liked",
    "Published model": "Published",
    "Purchased Model": "Purchased",
    "Setting": "Setting",
    "My Model": "My Models",
    "My 3D Printer": "My 3D Printer",
    "View All Printers": "View All Printers",
    "User Points": "User Points",
    "Points": "Points",
    "Sign out": "Sign out",
    "Activated": "Activated",
    "Bind": "Bind",
    "Activate": "Activate",
    "Unbind": "Unbind",
    "Unbind Successfully": "Unbind Succeeded",
    "Failed to Unbind": "Failed to Unbind",
    "Binding Successfully": "Binding Succeeded",
    "Activation Succeeded": "Activation Succeeded",
    "Serial Number": "Serial Number",
    "Activation Status": "Activation Status",
    "Binding Status": "Binding Status",
    "User Login": "User Login",
    "Sign In": "Sign In",
    "Sign Up": "Sign Up",
    "Remember Me": "Remember Me",
    "Login Failed": "Login Failed",
    "Username/Email": "Username/Email",
    "User does not Existed": "User does not Exist",
    "Please enter your username and password": "Please enter your username and password",
    "Please enter user name": "Please enter user name",
    "Please enter your password": "Please enter your password",
    "Login Timeout": "Login Timeout",
    "Network Problems and Please Try Later": "Network Problem. Please Try Later",
    "Password is Incorrect": "Password is Incorrect",
    "User Account has not been Activated": "User Account has not been Activated",
    "Forgot Password?": "Forgot Password?",
    "Username": "Username",
    "Email": "Email",
    "Password": "Password",
    "Confirm Password": "Confirm Password",
    "3-20 Characters Starting with a Letter": "3-20 Characters Starting with a Letter",
    "Enter an Email Address": "Enter an Email Address",
    "6-32 Characters": "6-32 Characters",
    "Input Password Again": "Input Password Again",
    "Registration means you agree with": "Registration means you agree with",
    "Tiertime User Agreement": "Tiertime User Agreement",
    "Username has been used": "Username has been used",
    "Invalid Username": "Invalid Username",
    "Email account has been used": "Email account has been used",
    "Invalid Email Address": "Invalid Email Address",
    "Invalid Password": "Invalid Password",
    "Passwords Do Not Match": "Password Does Not Match",
    "Parameters Error": "Parameters Error",
    "Congratulations": "Congratulations",
    "Registration is successful. An activation code has been sent to your email account.": "Registration was successful. An activation code has been sent to your email account.",
    "Retrieve Password": "Retrieve Password",
    "Email Adress does not exist or send a message to failure": "Email Address does not exist or failed to send an email",
    "An email to reset your password has been sent to your email address": "An email to reset your password has been sent to your email address",
    "Category": "Category",
    "Price": "Price",
    "All": "All",
    "Charge": "Paid",
    "Free": "Free",
    "Please sign in your account": "Please sign in your account",
    "Description": "Description",
    "Purchase": "Purchase",
    "Purchased": "Purchased",
    "Unpublish": "Unpublish",
    "Publish Model": "Publish Model",
    "Model Name": "Name",
    "Model Size": "Size",
    "Print Times": "Print Times",
    "Model Price": "Point",
    "Collection": "Like",
    "Collected": "Liked",
    "Download All": "Download All",
    "Model Infomation": "Model Infomation",
    "Package": "Package",
    "Plesae enter the model name": "Plesae enter the model name",
    "Model Price(points)": "Model Price(points)",
    "Unlimited": "Unlimited",
    "Publish": "Publish",
    "Pull down to refresh": "Pull down to refresh",
    "Release to refresh immediately": "Release to refresh immediately",
    "Refreshing datas…": "Refreshing data…",
    "Pull up can load more data": "Pull up can load more data",
    "Release to load more data immediately": "Release to load more data immediately",
    "Loading more datas…": "Loading more data…",
    "Sure to buy?": "Confirm Purchase?",
    "Unpublish successful": "Unpublish succeeded",
    "Published successfully": "Publish succeeded",
    "Your points is not enough!": "Your points are not enough!",
    "Purchase failed. Please try again": "Purchase failed. Please try again",
    "Plesae enter the model price": "Plesae enter the model price",
    "No Datas": "No Data",
    "Please enter a price for pure numbers": "Please enter a price for pure numbers",
    "Prepare...": "Preparing...",
    "Being slicing, can not import model":"Being slicing, can not import model",
    "No material detected, please replace it":"No material detected, please replace it",
    "Auditing":"Auditing",
    "Privacy Policy":"Privacy Policy",
    "privacyText":"Please review Tiertime Privacy Policy to know about the details of data collection of Tiertime.You can choose to turn on or off the data collection function base on your preference.",
    "View details":"View details",
    "Purchase success":"Purchase success",
    "Model purchase choices":"Model purchase choices",
    "Customize":"Customize",
    "Purchase quantity":"Purchase quantity",
    "Single-pass printing":"Single-pass printing(points)",
    "Unlimited printing":"Unlimited printing(points)"
	},
	"image": {}
}
